name: Magazín - Nightly Refresh
on:
  schedule: [ { cron: "0 4 * * *" } ]
  workflow_dispatch:
permissions: { contents: write }
env:
  SITE_BASE_URL: https://magazin.tvojehnizdo.com

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Generate articles (optional)
        if: ${{ secrets.OPENAI_API_KEY != '' }}
        env: { OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} }
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi
          if [ -f "generate_article.py" ]; then python generate_article.py || echo "skip"; fi

      - name: Rebuild sitemap & RSS
        env: { SITE_BASE_URL: ${{ env.SITE_BASE_URL }} }
        run: python tools/generate_site_assets.py || true

      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm i -g vercel
      - run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}